// <auto-generated />
namespace PBL3___Cosmetics_Store_Management_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Import : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Import));
        
        string IMigrationMetadata.Id
        {
            get { return "202406121201223_Import"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
